### ISSUE TITLE
FIXED: Text and Audio Bugs.

### ISSUE THREAD

**Issue by POPLOPUK** [htmlgames/htmlgames.github.io#1]
Weird Sound. Text messed up.

https://scratch.mit.edu/projects/113425296/
https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#113425296
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36

**Comment by htmlgames** [comment]
Hello POPLOPUK and thank you for starting off the issues with your project,
 Regarding the sound issue: this is a limitation of the javascript wav decoder - you may have noticed how some other projects sound cleaner, this is due to how the wav was orginally encoded.
 And the text I'm guessing is svg which also has limitations from being emulated via javascript.

This may be fixed in a future release, however I'd rather spend my limited time getting stuff like lists to display :)

**Comment by htmlgames** [comment]
FYI: https://phosphorus.github.io/#113425296
have now implemented a decent wav sound player

**Comment by htmlgames** [comment]
I've implemented the above method from phosphorus. Sound is now cleaner.

**Comment by htmlgames** [comment]
SVG's can be made cleaner (no anti-aliasing) by adding this css into player.css:

img {
  image-rendering:optimizeSpeed;             /* Legal fallback */
  image-rendering:-moz-crisp-edges;          /* Firefox        */
  image-rendering:-o-crisp-edges;            /* Opera          */
  image-rendering:-webkit-optimize-contrast; /* Safari         */
  image-rendering:optimize-contrast;         /* CSS3 Proposed  */
  image-rendering:crisp-edges;               /* CSS4 Proposed  */
  image-rendering:pixelated;                 /* CSS4 Proposed  */
  -ms-interpolation-mode:nearest-neighbor;   /* IE8+           */
}
